[[rulesets]]
years = [2023, 2024]
directory = "2023-centerstage"
shortname = "CENTERSTAGE"
longname = "CENTERSTAGE℠ presented by RTX"

[[rulesets.sources]]
directory = "general"

[rulesets.sources.resource]
href = "https://firstinspiresst01.blob.core.windows.net/first-in-show-ftc/game-manual-part-2-traditional.pdf"
name = "Game Manual Pt. 2"
anchor = "manual-gm2"
accessed = "2023-10-26T00:00:00-07:00"
section = "4.5.2"
section-name = "General Rules"

[[rulesets.sources]]
directory = "game-specific"

[rulesets.sources.resource]
href = "https://firstinspiresst01.blob.core.windows.net/first-in-show-ftc/game-manual-part-2-traditional.pdf"
name = "Game Manual Pt. 2"
anchor = "manual-gm2"
accessed = "2023-10-26T00:00:00-07:00"
section = "4.5.3"
section-name = "Game-Specific Rules"

[[rulesets.sources]]
directory = "safety"

[rulesets.sources.resource]
href = "https://firstinspiresst01.blob.core.windows.net/first-in-show-ftc/game-manual-part-2-traditional.pdf"
name = "Game Manual Pt. 2"
anchor = "manual-gm2"
accessed = "2023-10-26T00:00:00-07:00"
section = "4.5.1"
section-name = "Safety Rules"

# QA **must** be loaded last as it refers to, and modifies the in-memory objects
# of, rules defined in all above sections!
[[rulesets.sources]]
directory = "qa"

[rulesets.sources.resource]
href = "https://ftc-qa.firstinspires.org/rss/answers.rss"
name = "Q&A"
anchor = "qa"
accessed = "2023-11-03T19:00:00-07:00"

[rulesets.source-material]
# The TOML spec may natively understand RFC 3339 dates, but evidently
# something about the TOML crate does not: removing the strings here results in a
# deserialization error complaining about an invalid type "map".
accessed = "2023-10-26T00:00:00-07:00"
gm1-traditional = "https://firstinspiresst01.blob.core.windows.net/first-in-show-ftc/game-manual-part-1-traditional.pdf"
gm2-traditional = "https://firstinspiresst01.blob.core.windows.net/first-in-show-ftc/game-manual-part-2-traditional.pdf"

# [[rulesets]]
# years = [2022, 2023]
# directory = "2022-powerplay"
# shortname = "POWERPLAY"
# longname = "POWERPLAY℠ presented by Raytheon Technologies"
