[[rulesets]]
championship_year = 2025
program = "FTC"
directory = "2025-into-the-deep"
shortname = "Into The Deep"
longname = "Into The Deep℠ presented by RTX"

[rulesets.source_material]
accessed = "2024-10-18 17:54:05-07:00"
href = "https://ftc-resources.firstinspires.org/file/ftc/game/manual"
latest_team_update_included = 3

[[rulesets.sources]]
display_name = "Game Rules: Personal Safety (11.1)"
directory = "g1xx-safety"

[[rulesets.sources]]
display_name = "Game Rules: Conduct (11.2)"
directory = "g2xx-conduct"

[[rulesets.sources]]
display_name = "Game Rules: Pre-Match (11.3)"
directory = "g3xx-prematch"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Auto (11.4.1)"
directory = "g41x-auto"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Teleop (11.4.2)"
directory = "g42x-teleop"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Scoring Element (11.4.3)"
directory = "g43x-scoring-element"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Robot (11.4.4)"
directory = "g44x-match-robot"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Opponent Interaction (11.4.5)"
directory = "g45x-opponent-interaction"

[[rulesets.sources]]
display_name = "Game Rules: In-Match: Human (11.4.6)"
directory = "g46x-match-human"

[[rulesets.sources]]
display_name = "Game Rules: Post-Match (11.5)"
directory = "g5xx-postmatch"
